- .bit/config.yml
- .bit/responses/1.1-Week 1 Step 1.md
- .bit/responses/1.2-Week 1 Step 2.md
- .bit/responses/1.3-Week 1 Step 3.md
- .bit/responses/1.4-Week 1 Step 4.md
- .bit/responses/1.5-Week 1 Step 5.md
- .bit/responses/1.7-Week 1 Step 7.md
Added clarity, more screenshots, and better organization.
> Edits suggested by Daniel

- .bit/config.yml
- GETTING_STARTED.md
- README.md
Documentation on how to install the bot and get started with your camp.
> Create how-to documentation

- README.md
Put this image below into the README
> Add banner to README.md

- .bit/responses/1.1-Week 1 Step 1.md
- .bit/responses/1.2-Week 1 Step 2.md
- .bit/responses/1.4-Week 1 Step 4.md
Added descriptions for steps 1-4:
Closes issue #35 
Closes issue #37 
Closes issue #38 
Closes issue #39
> Week1 issues

- .bit/config.yml
- .bit/responses/1.7-Week 1 Step 7.md
- .bit/responses/2.a10-Week 2 Step 10.md
- .bit/responses/3.7-Week 3 Step 7.md
Edit config files to implement feedback step type that automatically logs student feedback.
> Implement Feedback Feature

- .bit/config.yml
- .bit/responses/1.1-Week 1 Step 1.md
- blog.md
closes #50  Need to create more issues for every heading for the blog
> Added Blog Template

- .bit/responses/3.5-Week 3 Step 5.md
> fixed 3.5 cosmos 

- .bit/responses/1.3-Week 1 Step 3.md
Added explanations for what everything we're doing actually is, with the hope that now the student will understand the why behind what's going on. I'm not an English major, so feel free to cannibalize this to fit Bit's writing style, etc. This is just the information I think would be helpful to have. 
Also fixed miscellaneous typos and whatnot that were present (at least the ones I caught).
> Making Week 1 Step 3 more beginner friendly

- .bit/responses/1.6-Week 1 Step 6.md
- .bit/responses/1.7-Week 1 Step 7.md
- .bit/tests/test.1.6.js
- .bit/workflows/week1.yml
- Add requirement to return image in base64
- new test
> Improve step 6

- .bit/responses/1.6-Week 1 Step 6.md
- .bit/tests/sample-solutions/week2/2.2-emotional.js
- .bit/tests/sample-solutions/week2/2.3-emotional.js
- .bit/tests/sample-solutions/week2/2.4-emotional.js
- .bit/tests/sample-solutions/week2/2.7-songrec.js
- .bit/tests/test.2.2.js
- .bit/tests/test.2.3.js
- .bit/tests/test.2.4.js
- .bit/tests/test.2.7.js
- Emotional Gifs
- SongRec
Edge case testing is required (Ex: if a student codes a function that has an unresolved promise - make sure the action doesn't pass)
> Week 2 Tests and Solutions

- .bit/tests/sample-solutions/week3/3.2-bunnimage.js
- .bit/tests/sample-solutions/week3/3.3-bunnimage.js
- .bit/tests/sample-solutions/week3/3.4-bunnimage.js
- .bit/tests/sample-solutions/week3/3.5-bunnimage.js
- .bit/tests/sample-solutions/week3/3.6-deepsecrets.js
- .bit/tests/sample-solutions/week3/3.7-deepsecrets.js
- .bit/tests/sample-solutions/week3/3.8-deepsecrets.js
- Bunnimage triggers
- Deep Secrets API
> Week 3 solutions

- .bit/responses/2.2-Week 2 Step 2.md
> Week 2 Step 2 feedback

- .bit/responses/2.6-Week 2 Step 6.md
- .bit/responses/2.7-Week 2 Step 7.md
- .bit/responses/2.8-Week 2 Step 8.md
- Original project was modified
- Formatting may need updates
> Rest of Week 2 (steps 6-8)

- .bit/tests/test.3.1.js
- .bit/tests/test.3.2.js
- .bit/tests/test.3.3.js
- .bit/tests/test.3.5.js
- .bit/tests/test.3.6.js
- .bit/tests/test.3.7.js
- .bit/tests/test.3.8.js
- Deep secrets
- Bunnimage
closes #151
> Week 3 Tests

- .bit/responses/1.2-Week 1 Step 2.md
- .bit/responses/1.3-Week 1 Step 3.md
- .bit/responses/1.5-Week 1 Step 5.md
- .bit/tests/test.1.5.js
- GETTING_STARTED.md
- README.md
- add more documentation about actions + moving on
- edited test for clarity
Closes #169 
Closes #106
> Applied Marc's feedback

- .bit/config.yml
- .bit/responses/4.2-Week 4 Step 2.md
- .bit/responses/4.3-Week 4 Step 3.md
- .bit/responses/4.4-Week 4 Step 4.md
- .bit/responses/4.5-Week 4 Step 5.md
- .bit/responses/4.6-Week 4 Step 6.md
- .bit/responses/4.7-Week 4 Step 7.md
- .bit/workflows/week4.yml
- Split issues
- Cypress integration
Closes #176
> Week 4 config update

- .bit/tests/sample-solutions/week2/2.5-emotional.js
- .bit/tests/test.1.4.js
- .bit/tests/test.1.5.js
- .bit/tests/test.1.6.js
- .bit/tests/test.1.7.js
- .bit/tests/test.1.8.js
- .bit/tests/test.2.2.js
- .bit/tests/test.2.3.js
- .bit/tests/test.2.4.js
- .bit/tests/test.2.5.js
- .bit/tests/test.2.6.js
- .bit/tests/test.2.7.js
- .bit/tests/test.2.8.js
- .bit/tests/test.3.1.js
- .bit/tests/test.3.2.js
- .bit/tests/test.3.3.js
- .bit/tests/test.3.5.js
- .bit/tests/test.3.6.js
- .bit/tests/test.3.7.js
- .bit/tests/test.3.8.js
- .bit/tests/test.4.6.js
- .bit/workflows/week2.yml
- added a bunch of try-catch statements
Closes #187
> Making tests edge case proof + weeks 1 & 2 testing

- .bit/tests/sample-solutions/week3/3.2-bunnimage.js
- .bit/tests/sample-solutions/week3/3.3-bunnimage.js
- .bit/tests/test.3.2.js
- .bit/tests/test.3.3.js
- .bit/tests/test.3.5.js
- .bit/tests/test.3.7.js
- .bit/tests/test.3.8.js
- Week 3 tests have been hardened
- Week 4 tests require testing in the Github Action environment
Closes #197
> Weeks 3/4 Tests

- .bit/config.yml
- .bit/responses/3.9-Week 3 Step 9.md
- .bit/responses/4.8-Week 4 Step 8.md
- .bit/workflows/week3.yml
- .bit/workflows/week4.yml
- Added missing livestream feedback files
- Fixed workflow count configs
- updated yaml
> Weeks 3 + 4 config

- .bit/responses/1.2-Week 1 Step 2.md
- .bit/responses/4.3-Week 4 Step 3.md
- .bit/responses/4.6-Week 4 Step 6.md
- .bit/responses/4.7-Week 4 Step 7.md
- .bit/tests/sample-solutions/week4/4.3/script.js
- .bit/tests/sample-solutions/week4/4.4/script.js
- cypress/integration/4.3.spec.js
- cypress/integration/4.7.spec.js
> Week 4 Test + Content fixes

- .bit/tests/wrongbranch.js
- .bit/workflows/week1.yml
- .bit/workflows/week2.yml
- .bit/workflows/week3.yml
- .bit/workflows/week4.yml
Catches the case if a student accidentally forgets to create a new branch.
> Checks if the count on the particular branch is equivalent to the last step of the week.
Closes #209
> Workflow updates

- .bit/responses/2.5-Week 2 Step 5.md
- .bit/responses/2.6-Week 2 Step 6.md
> Step 5 and 6 Week 2 Fixes

- .bit/responses/1.4-Week 1 Step 4.md
- .bit/responses/1.5-Week 1 Step 5.md
- .bit/responses/1.6-Week 1 Step 6.md
- .bit/responses/1.7-Week 1 Step 7.md
- .bit/responses/1.8-Week 1 Step 8.md
- .bit/responses/2.2-Week 2 Step 2.md
- .bit/responses/2.3-Week 2 Step 3.md
- .bit/responses/2.4-Week 2 Step 4.md
- .bit/responses/2.5-Week 2 Step 5.md
- .bit/responses/2.6-Week 2 Step 6.md
- .bit/responses/2.7-Week 2 Step 7.md
- .bit/responses/2.8-Week 2 Step 8.md
- .bit/tests/test.1.4.js
- .bit/tests/test.1.5.js
- .bit/tests/test.1.6.js
- .bit/tests/test.2.2.js
> Changed file names and tests

- .bit/responses/1.4-Week 1 Step 4.md
- .bit/responses/1.5-Week 1 Step 5.md
- .bit/responses/1.6-Week 1 Step 6.md
- .bit/responses/1.7-Week 1 Step 7.md
- .bit/responses/1.8-Week 1 Step 8.md
- .bit/responses/2.2-Week 2 Step 2.md
- .bit/responses/2.3-Week 2 Step 3.md
- .bit/responses/2.4-Week 2 Step 4.md
- .bit/responses/2.5-Week 2 Step 5.md
- .bit/responses/2.6-Week 2 Step 6.md
- .bit/responses/2.7-Week 2 Step 7.md
- .bit/responses/2.8-Week 2 Step 8.md
- .bit/tests/test.1.4.js
- .bit/tests/test.1.5.js
- .bit/tests/test.1.6.js
- .bit/tests/test.2.2.js
Reverts bitprj/Intro-To-Serverless#238
> Revert "Changed file names and tests"

- .bit/responses/1.4-Week 1 Step 4.md
- .bit/responses/1.5-Week 1 Step 5.md
- .bit/responses/1.6-Week 1 Step 6.md
- .bit/responses/1.7-Week 1 Step 7.md
- .bit/responses/1.8-Week 1 Step 8.md
- .bit/responses/2.2-Week 2 Step 2.md
- .bit/responses/2.3-Week 2 Step 3.md
- .bit/responses/2.4-Week 2 Step 4.md
- .bit/responses/2.5-Week 2 Step 5.md
- .bit/responses/2.6-Week 2 Step 6.md
- .bit/responses/2.7-Week 2 Step 7.md
- .bit/responses/2.8-Week 2 Step 8.md
- .bit/tests/test.1.4.js
- .bit/tests/test.1.5.js
- .bit/tests/test.1.6.js
- .bit/tests/test.2.2.js
Reverts bitprj/Intro-To-Serverless#239
> Revert "Revert "Changed file names and tests""

- .bit/responses/1.8-Week 1 Step 8.md
- .bit/responses/2.3-Week 2 Step 3.md
Added a description of the keys needing to be coded locally and not using process.env.
closes  #255
> Week 2 step 3 keys

- .bit/responses/1.8-Week 1 Step 8.md
- .bit/responses/2.7-Week 2 Step 7.md
Updated the ranges to be more clear with no overlap, and also fixed the example code to match.
Closes #258 
Closes #260
> Week 2 step 7 ranges

- .bit/responses/2.1-Week 2 Step 1.md
Added a screenshot showing how to choose `POST` from the dropdown.
Closes #268
> added post request screenshot

- .bit/responses/2.2-Week 2 Step 2.md
Added bullet points to specify using form-data. Also added that you don't ned to specify a key and can just send a value, and how to change from text to file sending.
Closes #264
> Week 2 Step 2 added form-data specify

- .bit/responses/2.3-Week 2 Step 3.md
Fixes function secrets to application settings to make it more clear and consistent
Closes #272
> Update 2.3-Week 2 Step 3.md

- .bit/responses/2.7-Week 2 Step 7.md
| Generation  | Range         |
|-------------|---------------|
| GenZ        | 5 < age < 25  |
| GenY        | 24 < age < 41  |
| GenX        | 40 < age < 57  |
| BabyBoomers | 56 < age < 76  |
| Unknown     | Any other age |
> Fixed the ranges

- .bit/responses/1.5-Week 1 Step 5.md
Change code from `git pull` to `git pull origin [BRANCH_NAME]`
Closes #278
> Git pull origin [Branch_name]

- .bit/responses/3.4-Week 3 Step 4.md
Changed from run the function to run using `node index.js`
Closes #284
> run with nodejs

- .bit/responses/4.1-Week 4 Step 1.md
also changed the code type to html from diff
Closes #287
> remvoed the plus signs

- .bit/responses/3.6-Week 3 Step 6.md
> added mention that maybe won't receive text back

- .bit/responses/4.3-Week 4 Step 3.md
Added the `FormData` object + a description of how to use it. Also added instructions to make HTML id
Closes #290
> Added formdata object

- .bit/responses/3.7-Week 3 Step 7.md
Change from just `message = 'value'` to `let message = 'value'`
Closes #286
> declared message with `let`

- .bit/responses/4.1-Week 4 Step 1.md
- .bit/responses/4.5-Week 4 Step 5.md
Added that `!` + `Tab` will create a HTML template for you in vscode
Closes #292
> Week 4 step 5 template

- .bit/responses/3.3-Week 3 Step 3.md
- .bit/tests/sample-solutions/week3/3.3-bunnimage.js
- .bit/tests/test.3.3.js
Closes #277 
- Implemented new solution code in sample solutions and instructions
- Added `body: ''` to the test
> Fix Week 3 Step 3 test and solution code

- .bit/responses/4.1-Week 4 Step 1.md
- .bit/responses/4.2-Week 4 Step 2.md
@emsesc can you check that the bot checks that the id of the filename input is `username` and not `name`?
I changed the `name` id's to `username` id's in step 1 b/c my final code used `username` and that passed the test. Check to make sure that `username` id will still pass the test in step 1 and 2. 
Closes #288
> Week 4 step 1 and 2

- .bit/tests/test.2.7.js
Added extra debug data to resolve https://github.com/bitprj/Intro-To-Serverless/issues/306
> Added debugging to tests to resolve issue 306

- .bit/responses/2.4-Week 2 Step 4.md
Used (in my opinnion) a simplier approach to find the highest value emotion. 
```
function determineDom(emotionJSON) {
let maxValue = 0;
let domEmo;
for (var emo in emotionJSON) {
if (emotionJSON[emo] > maxValue) {
maxValue = emotionJSON[emo];
domEmo = emo;
}
}
return domEmo
}
```
I think this would be easier for beginners to understand, but that might just be me, because it is a little bit more code than the original one line.
Also, we might need to create a video explaining this code if we do use it. It's fine if we don't use this code, i just thought i would rewrite it.
Closes #270
> rewrote code to find the max value emotion

- .bit/tests/test.1.5.js
Fixes https://github.com/bitprj/Intro-To-Serverless/issues/308
> Updated error message for Issue 308

- .bit/responses/3.7-Week 3 Step 7.md
* Changed only one parameter of `client` to `client`, `databseId`, and `containerId`.
Closes #324
> update parameter wording

- .bit/responses/3.7-Week 3 Step 7.md
- .gitignore
* Added lines specifying the process.ENV endpoint and key are for the cosmo database and attached images for ease of use. 
* I modified the code to reference COSMO_ENDPOINT and COSMO_KEY
* This change was for clarification as at this point in time we already have a ENDPOINT and KEY in the Function App Setting but that references the Face API, we need to say that the ennpoint and key are for the cosmo database
Closes #325
> omr issue325

- GETTING_STARTED.md
* Added an extensions section to include in getting started
* Added azure tools & eslint, and linked a yt video on how to use eslint with vscode.
Closes #322
> added extensions section

- .bit/responses/3.7-Week 3 Step 7.md
changed given code to get students to read the documentation instead
docs: https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-nodejs-get-started
* Replaced most of the given code to create and query the db with documentation links.
Closes #332
> Week 3 Step 7 Read Documentation Change

- GETTING_STARTED.md
* Created a general debugging guide with the steps given in the issue.
* Added a yt video and vscode tutorial on how to use some of the debugging tips
Closes #257
> general debugging guide

- .bit/responses/3.4-Week 3 Step 4.md
- .bit/responses/3.5-Week 3 Step 5.md
* Changed `const account = "YOUR_ACCOUNT_NAME";` to `const account = "YOUR_STORAGE_ACCOUNT_NAME";` in step 4.
* Changed `"downloadUri" : "https://<YOUR_BLOB_STORAGE_URL>.blob.core.windows.net/images/<USERNAME>.png"` to `"downloadUri" : "https://<YOUR_STORAGE_ACCOUNT_NAME>.blob.core.windows.net/images/<USERNAME>.png"` in step 5
Closes #317
> Week 3 step 4 codename

- .bit/responses/1.8-Week 1 Step 8.md
* Added code to make sure week 1 morse code checks for an empty `plaintext`, or if `plaintext` was not entered at all.
Closes #252
> check for nothing in plaintext

- .bit/responses/1.8-Week 1 Step 8.md
* Removed old screenshots for Azure portal
* Specified to use VSCode
Closes #256
> Make sure students use VSCode

- .bit/responses/3.7-Week 3 Step 7.md
- .bit/responses/3.8-Week 3 Step 8.md
* Specifically stated that the message format **must be the same**
Closes #326
> Week 3 Steps 7/8 answer format

- .bit/responses/2.6-Week 2 Step 6.md
- .bit/responses/3.6-Week 3 Step 6.md
- .bit/responses/3.7-Week 3 Step 7.md
- .bit/tests/sample-solutions/week2/2.6-songrec.js
- .bit/tests/sample-solutions/week2/2.7-songrec.js
- .bit/tests/sample-solutions/week2/2.8-songrec.js
- .bit/tests/sample-solutions/week3/3.6-deepsecrets.js
- .bit/tests/sample-solutions/week3/3.7-deepsecrets.js
- .bit/tests/sample-solutions/week3/3.8-deepsecrets.js
- .bit/tests/sample-solutions/week3/deepsecrets.js
* querystring is deprecated, so changed to use npm package qs.
* Code has been tested to work.
* Sample solutions have been updated
Closes #305
> Change querystring to qs

- README.md
* Added a gif to the readme that is an example of what a final project could look like
> added example final project

- .bit/responses/2.2-Week 2 Step 2.md
* Replaced the azure screenshot with a screenshot of my vscode terminal
Closes #266
> added npm init ss

- .bit/responses/4.1-Week 4 Step 1.md
* Added `for` in the label
* Added `aria-label` in the input
Closes #358
> accessibility fixes

- .bit/responses/1.7-Week 1 Step 7.md
> Update 1.7-Week 1 Step 7.md

- .bit/responses/2.2-Week 2 Step 2.md
* [Replace with summaries of general changes made]
* [Did you modify or delete?]
* [How do your changes fix the issue?]
Closes #[issue number]
> Update 2.2-Week 2 Step 2.md

- .bit/responses/2.5-Week 2 Step 5.md
> Update 2.5-Week 2 Step 5.md

- .bit/responses/2.6-Week 2 Step 6.md
> Update 2.6-Week 2 Step 6.md

- .bit/responses/3.2-Week 3 Step 2.md
> Update 3.2-Week 3 Step 2.md

- .bit/responses/3.3-Week 3 Step 3.md
> Update 3.3-Week 3 Step 3.md

- .bit/responses/3.5-Week 3 Step 5.md
> Update 3.5-Week 3 Step 5.md

- .bit/responses/3.8-Week 3 Step 8.md
> Update 3.8-Week 3 Step 8.md

- .bit/responses/4.3-Week 4 Step 3.md
> Update 4.3-Week 4 Step 3.md

- .bit/responses/4.2-Week 4 Step 2.md
* Deleted onsubmit in html
* Deleted verbiage referencing getImage function
> Update 4.2-Week 4 Step 2.md

- .bit/responses/4.1-Week 4 Step 1.md
* I removed the onlick event to keep javascript separate from html (coding convention)
* I removed the getImage function and replaced it with an anonymous function triggered by an event listener
* I removed all verbiage associated with the getImage function
* The next several steps will need to be modified to match this approach
> Update 4.1-Week 4 Step 1.md

- .bit/responses/4.2-Week 4 Step 2.md
* Use JS for form validation 
* https://stackoverflow.com/questions/8231058/file-type-validation-with-javascript
* https://stackoverflow.com/questions/857618/javascript-how-to-extract-filename-from-a-file-input-control
Closes #380
> Use JS for form validation

- .bit/tests/sample-solutions/week4/4.1/index.html
- .bit/tests/sample-solutions/week4/4.1/script.js
- .bit/tests/sample-solutions/week4/4.2/index.html
- .bit/tests/sample-solutions/week4/4.2/script.js
- .bit/tests/sample-solutions/week4/4.3/index.html
- .bit/tests/sample-solutions/week4/4.3/script.js
- .bit/tests/sample-solutions/week4/4.4/index.html
- .bit/tests/sample-solutions/week4/4.4/script.js
- .bit/tests/sample-solutions/week4/4.5/index.html
- .bit/tests/sample-solutions/week4/4.5/script.js
- .bit/tests/sample-solutions/week4/4.7/index.html
- .bit/tests/sample-solutions/week4/4.7/script.js
* Updated the sample solutions for the steps with updated event listeneres and such. 
Closes #377
> Week 4 sample solutions

- .bit/config.yml
- .bit/responses/1.2-Week 1 Step 2.md
- .bit/responses/1.9-Week 1 Step 9.md
- .bit/responses/2.5-Week 2 Step 5.md
- .bit/responses/2.9-Week 2 Step 9.md
- .bit/responses/3.2-Week 3 Step 2.md
- .bit/responses/3.5-Week 3 Step 5.md
- .bit/responses/3.9-Week 3 Step 9.md
- .bit/responses/4.8-Week 4 Step 8.md
* Delete "don't merge the PR" because every step is a separate issue
* Remove live stream wording and replaced with videos
Closes #400 
Closes #398
> Content revisions

- GETTING_STARTED.md
- README.md
> Create CounselorBot guide in Getting Started md

- .bit/responses/4.1-Week 4 Step 1.md
- .bit/tests/sample-solutions/week4/4.1-bunnimage/index.html
- .bit/tests/sample-solutions/week4/4.1-bunnimage/script.js
- bunnimage/index.html
- cypress/integration/4.1.spec.js
* Fixed inconsistencies in solution code
* Fixed bug in Week 4 Step 1 Test
> Week 4 Step 1

- cypress/integration/4.1.spec.js
Cypress is not compatible with event.preventDefault()
* Removed requirement in testing to check final output
> Week 4 Step 1 Test Edits

- .bit/responses/1.1-Week 1 Step 1.md
* Added to checklist that specifies draft PR
* Added a section that explains when you could use a draft PR
Closes #399
> Week 1 Step 1 Draft PR Requirement

- .bit/tests/sample-solutions/week1/1-2.helloworld.js
Used ";" to finalize statement to be consistent with overall notation in exercises/solutions
Closes #411
> Issue #411 - consistent usage of ";" in week 1 ex 1.2

- .bit/responses/1.8-Week 1 Step 8.md
- Fixed editorial issues from #446 
- changes in layout to reduce linting errors
Closes #446
> Response Week 1 Step 8 - Editorial fixes

- .bit/tests/sample-solutions/week1/1.5-hackervoice.js
- added missing semicolons
- added strict comparison
Closes #415
> Fixed inconsistent usage of semicolon and value comparison (issue #415)

- .bit/tests/sample-solutions/week1/1.6-twocatz.js
- Adjust the comment to point to node-fetch@v2
- Restructure the code for concise modularization and improvement of readability
- Usage of `const` over `let` where possible
Closes #417
> Fix for structure of helper function, usage of const and semicolon in Week 1 ex 1.6

- .bit/tests/sample-solutions/week1/1.7-twocatz.js
- Adjust structure of helper functions (follow up to issue #416  and PR #418 )
- Consistent variable naming
- Explicit array creation for names
- Consistent usage of semicolons
Closes #419
> Week 1 ex 1.7 - Struture of helper functions etc.

- .bit/tests/sample-solutions/week1/1.8-morse-code.js
- Implement check if query parameter is provided and return message if not
- Add comment on nom package to install (as for ex 1.6 and 1.7 in week 1
Closes #421
> Fix Week 1 ex 1.8 - Basic input validation

- .bit/tests/sample-solutions/week2/2.2-emotional.js
- usage of `const` where possible 
- removed `fetch` module as not used
- added semicolons
- removed `context.done()`
- Changed comments
Closes #423
> Sample Solution  Week 2 ex 2.2. - Several fixes for consistency

- .bit/tests/sample-solutions/week2/2.3-emotional.js
- Usage of semicolons
- Usage of `const`
- Removal of `context.done()`
- format of file
Closes #425
> Sample Solution Week 2 ex 2.3 - Several fixes for consistency

- .bit/tests/sample-solutions/week2/2.4-emotional.js
- Use `const` where possible
- format code
- remove `context.done()`
- consistent naming variables (lowerCamelCase)
Closes #427
> Sample Solution  Week 2 ex 2.4 - Several fixes for consistency

- .bit/tests/sample-solutions/week2/2.5-emotional.js
Same fixes as in PR #428 as exercise is an evolution of the code created there
Closes #429
> Sample Solution  Week 2 ex 2.5 - Several fixes for consistency

- .bit/tests/sample-solutions/week2/2.6-songrec.js
- usage of semicolons
- declaration of variables
Closes #431
> Sample Solution Week 2 ex 2.6 - Several fixes for consistency

- .bit/tests/sample-solutions/week2/2.7-songrec.js
- usage of `const` instead of `var` oor undeclared values
- usage of assigned variables
- usage of semicolons
Closes #433
> Sample Solution Week 2 ex 2.7 - Several fixes for consistency

- .bit/tests/sample-solutions/week2/2.8-songrec.js
- structure of code consistent with previous exercise
- remove unused variables
- usage of `const`
- naming of variables with the code reviewer in mind :-)
- usage of semicolons
Closes #435
> Sample Solution Week 2 ex 2.8 - Several fixes for consistency

- .bit/responses/1.2-Week 1 Step 2.md
- Use of const in code samples
- Elaborate more on the Node.js version (Azure Functions only run on LTS versions)
- Format detail step for git (mixture of numbers and bullet points) with correct indentation
- Fixing linting error in markdown
Closes #440
> Issues in response of week1 step 2

- .bit/responses/1.6-Week 1 Step 6.md
- add line break ">"
- exchange `let` with `const` in code snippets
- 
Closes #444
> Fixes for repsonse week1 step 6

- .bit/tests/sample-solutions/week3/3.5-bunnimage.js
- parameter of file name is handed over via route
- check of request is done via HTTP status 
- usage of `const` instead of `var`
Closes #466
> Improvements week3 - sample solution step 5

- .bit/tests/sample-solutions/week3/3.4-bunnimage.js
- Usage of the `deleteBlob` method on the container client
- Added some additional information in the comments esp. for local execution of the function
Closes #464
> Improvements week3 - sample solution step 4 with usage of deleteBlob

- .bit/config.yml
- .bit/responses/3.4-Week 3 Step 4.md
- .bit/tests/sample-solutions/week3/3.4-bunnimage.js
* changed explanation
* edited solution code
* edited instruction files
* fixed "moving on" configuration
Closes #454
> Week 3 Step 4 Fixes

- .bit/tests/sample-solutions/week3/3.3-bunnimage.js
- adjust code to fit to week 2
- transfer filename via route parameter
Closes #462
> Improvements week3 - sample solution step 3

- .bit/tests/sample-solutions/week3/3.6-deepsecrets.js
- switched to Twilio setup according to documentation
Closes #468
> Improvements week3 - sample solution step 6 - Interaction with Twilio

- .bit/tests/sample-solutions/week3/3.2-bunnimage.js
- Usage of `const` and `let`
- Handling of unsupported files types via status 400 of response
- Separate determination of extension for file type in a function
- Using `context.log` for logging
- Improve logging messages 
- Connection string isfetched in function not as a global variable
Closes #460
> Improvements week3 - sample solution step 2

- .bit/responses/1.3-Week 1 Step 3.md
- .bit/responses/1.6-Week 1 Step 6.md
- .bit/responses/1.7-Week 1 Step 7.md
- .bit/responses/3.1-Week 3 Step 1.md
- .bit/responses/3.4-Week 3 Step 4.md
- .bit/responses/4.5-Week 4 Step 5.md
* Week 3 Step 1
* Week 2 Step 2
* Week 3 step 4
- Added backup CataaS Endpoint (https://bit-cat.azurewebsites.net/cat/says/serverless)
- Added specification to install node-fetch@2
Closes #409 #407 #474 #410
> Small fixes in wording

- .bit/tests/sample-solutions/week4/4.6-twocatz/twocatz.js
- usage `const` where possible
- Structuring of function (main function mixed with "helper" function)
- Comment to use `node-fetch` version 2
- Update API for fetching Cat pictures
Closes #488
> Sample solution week 4 step 6 - fixes

- .bit/tests/sample-solutions/week4/4.5-twocatz/index.html
- .bit/tests/sample-solutions/week4/4.5-twocatz/script.js
- remove CSS references
- correct  file type of image in `index.html`
-  location of script after body
- Update API for cat pics retrieval
Closes #486
> Sample solution week 4 step 5 - fixes

- .bit/tests/sample-solutions/week4/4.2-bunnimage/index.html
- .bit/tests/sample-solutions/week4/4.2-bunnimage/script.js
* Remove CSS references (or provide css file)
* Place script at end of body
* Remove import of jquery
* Remove image reference
* Check file type via File API
* Update of year in Copyright
Closes #480
> Sample solution week 4 step 2 - Fixes

- .bit/tests/sample-solutions/week4/4.1-bunnimage/index.html
- .bit/tests/sample-solutions/week4/4.1-bunnimage/script.js
* Removal of CSS
* Putting the script tag at then end of the body
* Adjustment of  the title
* update of year on copyright statement
Closes #478
> Sample Solution week 4 step 1 - Fixes

- .bit/tests/sample-solutions/week3/3.7-deepsecrets.js
- .bit/tests/sample-solutions/week3/3.8-deepsecrets.js
- refactoring of code wrt to readability
- resiliency of code if no item is in the DB
I refactored step 7 and 8 in one PR to stay consistent
Open Issue: Adjustment of response concerning Twilio (see PR #469) 
Closes #470
> Improvements week3 - sample solution step 7 and 8

- .bit/responses/1.8-Week 1 Step 8.md
* Removed extra space
Closes #499
> #499 Remove space from sample

- .vscode/extensions.json
- GETTING_STARTED.md
* Removed plugin that is not longer avlaible
Closes #493
> #493 Removed Bracket Colour as now built in to VSCode

- GETTING_STARTED.md
* Added standard GitHub developer flow
* Added explanation for why setting up local checks is recommended
Closes #438
> Rewording instructions for running tests locally

- .bit/responses/1.4-Week 1 Step 4.md
* Clarifying "response body" (not function body)
* Disclaimer for NOT sending passwords in parameters
Closes #443
> Hackervoice Changes

- .bit/responses/4.1-Week 4 Step 1.md
* Changed sequence of steps for the HTML and event listener sections
* Added small edits for flow
Closes #475
> Week 4 Step 1 Refactor

- .bit/responses/3.7-Week 3 Step 7.md
* VS Code spelling
* Note about local development
* Serverless tier
* `let` to `const`
> **Note:** I did not apply the suggestions for Azure Key Vault (see issue) because this portion of Week 3 will be changed to introduce students to binding; therefore, Key Vault would not apply.
Closes #457
> Week 3 Step 7 Edits

- .bit/responses/3.8-Week 3 Step 8.md
* Explained best practices for querying data
* Added resources for real-world applications
Closes #458
> Selecting Random Data Warning

- .bit/responses/3.1-Week 3 Step 1.md
* LRS config
* Explain dangers of public endpoint
* Add note about storage explorer
Closes #451
> Week 3 Step 1 Revisions

- .bit/responses/3.2-Week 3 Step 2.md
* Added comparison of bindings and SDKs
* Consistent screenshot themes
* Added reminder on local.settings.json
* Added tip in testing to see what happens when two files of the same name are uploaded
Closes #452
> Week 3 Step 2 Revisions

- .bit/responses/1.3-Week 1 Step 3.md
* Added REST resource
* Added HTTP methods resource
Closes #442
> Add resources for w1s3

- .bit/responses/4.2-Week 4 Step 2.md
* Modified second drop down in input validation section
* Added links to correct documentation for the File API
Closes #476
> Week 4 Step 2 Input Validation
